### ISSUE TITLE
[NEW TEST] Custom Auth Guard Tests

### ISSUE THREAD

**Issue by steinroe** [jmcdo29/testing-nestjs#1105]
Hi, 

thanks for this repo - it helps a lot in figuring out how to test!

I am currently trying to write a test for an UserAuthGuard which extends the default AuthGuard and uses a custom strategy (Firebase Auth).

It basically just calls `super.canActivate()` to trigger the Firebase Auth and then checks if some decorators are set. My main concern is the `super.canActivate()` --> How can I mock that in a unit test? I guess this is rather jest specific, but I could not find anything useful there, too.

```
@Injectable()
export class UserAuthGuard extends AuthGuard('firebase')
  implements CanActivate {
  constructor(private reflector: Reflector) {
    super();
  }

  getRequest(context: ExecutionContext) {
    const ctx = GqlExecutionContext.create(context);
    return ctx.getContext().req;
  }

  async canActivate(context: ExecutionContext): Promise<boolean> {
    await super.canActivate(context);
    const request = this.getRequest(context);
    const user: AuthUser = request.user;

    if (user?.admin) return true;

    // adminOnly
    const adminOnly = this.reflector.get<boolean>(
      'adminOnly',
      context.getHandler(),
    );
    if (adminOnly) return false;

    // notEmployee
    const notEmployee = this.reflector.get<boolean>(
      'notEmployee',
      context.getHandler(),
    );
    if (notEmployee && user?.employee) return false;

    return true;
  }
}

```

**Comment by micalevisk** [comment]
What about `jest.spyOn(AuthGuard.prototype, 'canActivate').mockImplementation()` (https://stackoverflow.com/a/63762678/5290447) I didn't tested it.

**Comment by steinroe** [comment]
Sorry, I forgot about this issue. You're correct, the following worked out for me.

```
const spy = jest
      .spyOn(BaseAuthGuard.prototype, 'canActivate')
      .mockImplementation(async () => {
        return true;
      });
```

**Comment by oleksiifinkratt** [comment]
I also wanted to mock `super.canActivate()` in my custom implementation of JWT guard (`class JwtAuthGuard extends AuthGuard('jwt')`).

Thanks to the previous replies, I managed to mock it this way:
```
const parentCanActivateSpy = jest
  .spyOn(AuthGuard('jwt').prototype, 'canActivate')
  .mockImplementation(() => false);
```

First I tried spying on `AuthGuard.prototype`, but it didn't work. You need to pass the strategy like this: `AuthGuard('jwt').prototype`
