### ISSUE TITLE
Suggestion: convert testing-nestjs into monorepo with Lerna

### ISSUE THREAD

**Issue by omermorad** [jmcdo29/testing-nestjs#1222]
@jmcdo29 I thought about it, what do you think about changing this repo to work with Lerna where every sample will be a package? 😃 

Then we can manage a `CHANGELOG.md` file and use some Semver methodological as well

**Comment by jmcdo29** [comment]
The original idea behind the nest monorepo was to give the monorepo method a shot. Overall, I'd prefer a pnpm workspace over lerna (I like pnpm over the other packages managers), but if you want to try your hand at converting it, go for it :smile:

**Comment by omermorad** [comment]
I see. Actually, I've never used `pnpm` before.
So do you want to give `lerna` a shot with the classic `npm`?

Take into account it's going to be a big change :)
So after converting it we will need to merge it quickly in order to avoid merge hell

**Comment by jmcdo29** [comment]
`pnpm workspaces` are incredibly similar to `lerna` to be honest. I'll work on making the change though. It also supports the `workspace:` protocol, like `yarn` does, so they should be closely compatible. I haven't checked in `npm` supports that yet or not
