### ISSUE TITLE
Suggestion: create tests for Prisma (alternative to TypeORM)

### ISSUE THREAD

**Issue by felinto-dev** [jmcdo29/testing-nestjs#1268]
What do you think of creating a project with good testing practices using the ORM Prisma? It would be greatly appreciated.

**Comment by felinto-dev** [comment]
PS: I don't have any idea how I put the "bug" label. Could you remove it? Thanks.

**Comment by jmcdo29** [comment]
I could definitely see some use for it. Would you like to try your hand at a PR for this, following the examples for TypeORM, Mongoose, and Sequelize?

**Comment by felinto-dev** [comment]
I love to contribute to open-source projects, but the reason I'm suggesting this is partly because I don't have a clue how to do it.

**Comment by jmcdo29** [comment]
Fair enough! I'll try to get to this when I have some time then. I've got some other improvements I'd like to make too

**Comment by QimatLuo** [comment]
I need prisma example too.
I'm not really understand how to write test with prisma in nestjs even though prisma official website have example without nestjs.

**Comment by tak1n** [comment]
@QimatLuo there are a few discussion threads open on prisma side on how todo testing:

- https://github.com/prisma/prisma/discussions/2083
- https://github.com/prisma/prisma/discussions/7088

For e2e tests we use a similar approach like in Rails (I'm coming from a ruby/rails background). We basically have a test database (`dbname-test`) in which we apply the schema through `prisma migrate dev`, after that we just execute the e2e tests which truncates the tables after each test case (Rails is using [transactions](https://anti-pattern.com/transactional-fixtures-in-rails) for this, but currently [long running transactions](https://github.com/prisma/prisma/issues/1844#issuecomment-846477520) are not supported by prisma).

Here some examples of e2e tests:
```typescript
import request from 'supertest';
import { Test } from '@nestjs/testing';
import { INestApplication, ValidationPipe } from '@nestjs/common';
import { PrismaService } from '../src/prisma.service';
import { ProductsModule } from '../src/products/products.module';

describe('Products', () => {
  let app: INestApplication;
  let prisma: PrismaService;

  beforeAll(async () => {
    const moduleRef = await Test.createTestingModule({
      imports: [ProductsModule, PrismaService],
    }).compile();

    app = moduleRef.createNestApplication();
    prisma = moduleRef.get<PrismaService>(PrismaService);

    app.useGlobalPipes(new ValidationPipe({ whitelist: true }));

    await app.init();
  });

  afterAll(async () => {
    await app.close();
  });

  afterEach(async () => {
    // TODO: use transactions and transaction rollback once prisma supports it
    await prisma.truncate();
    await prisma.resetSequences();
  });

  it(`/products (GET)`, async () => {
    await prisma.product.createMany({
      data: products,
    });

    await request(app.getHttpServer())
      .get('/products')
      .expect(200)
      .expect((res) => {
        expect(res.body).toStrictEqual(
          expect.arrayContaining([expect.objectContaining(productShape)]),
        );
      });
  });

  it(`/products/:uuid (GET)`, async () => {
    const storedProduct = await prisma.product.create({
      data: product,
    });

    await request(app.getHttpServer())
      .get(`/products/${storedProduct.id}`)
      .expect(200)
      .expect((res) => {
        expect(res.body).toStrictEqual(expect.objectContaining(productShape));
      });
  });
});
```
Here the truncate method of the prisma service:
```typescript
  async truncate() {
    for (const { tablename } of await this
      .$queryRaw`SELECT tablename FROM pg_tables WHERE schemaname='public'`) {
      if (tablename !== '_prisma_migrations') {
        // eslint-disable-next-line no-await-in-loop
        await this.$queryRaw(`TRUNCATE TABLE "public"."${tablename}" CASCADE;`);
      }
    }
  }
```
Hope this helps you or someone else :)
I could also try to craft a PR once I have some time.

**Comment by jmcdo29** [comment]
Thanks for all the info on this. I plan on getting back to maintenance on this repo as of next week once I get back from vacation.
