### ISSUE TITLE
[NEW TEST] WebSockets

### ISSUE THREAD

**Issue by jmcdo29** [jmcdo29/testing-nestjs#14]
**Feature Test To Be Requested**

A test repository showing how to test web sockets could be really useful for some people. Full End to End testing too if possible

**Comment by ShGKme** [comment]
Tere is an issue with e2e testing.
```Jest did not exit one second after the test run has completed.```

To be honest, I can't understand, why this:
https://github.com/jmcdo29/testing-nestjs/blob/master/apps/websocket-sample/test/app.e2e-spec.ts#L23
will connect exacly to the testing app http server... How it works.

And what about adding about more "websocket" test. In this test event just return result like usual http endpoint. It'd be more interesting to return WsResponse (emit another event as an answer to subscribed event).

**Comment by jmcdo29** [comment]
@ShGKme I'll be 100% honest, I'm not completely sure how it works myself. I believe it has something to do with `socket.io` scanning already made connections via `socket.io`, and creating a client for it. If you have an idea for better tests I'd be happy to accept a PR for them. Websockets are still a bit out of my realm of knowledge so I went with a simple test for now. I'll re-open the issue for now as a reminder that better tests are needed. Maybe even one for non-socket.io clients

**Comment by ShGKme** [comment]
@jmcdo29 `io.connect();` doesn't really work.   
It's very funny. Let's look to the test:

```typescript
// It's an async test, so, it except Promise to be resolved.
it('should call message', async () => {
  // Connect to socket server (what server? does it know an address?)
  const socket = io.connect();
  // Does we connect successfully? connect never throw error itself...

  //Ok, let's emit a message
  socket.emit('message', { name: 'Test' }, (data) => {
    // (!)When(!) it'll receive an acknowledgement, we will check, that it's correct
    expect(data).toBe('Hello, Test!');
  });
  // (!) If we won't receive any acknowledgement from message event, we will check nothing :D

  // By the way, disconnect doesn't return Promise.
  return socket.disconnect();
});
```

The test will finish earler, than we will receive anything and won't check for any errors.
At the end, we have passed test with a Jest warning: 
> Jest did not exit one second after the test run has completed.
> This usually means that there are asynchronous operations that weren't stopped in your tests.

More fun? This will pass :D
```typescript
it('should call message', async () => {
  const socket = io.connect('http://THE_URL_THAT_DOES_NOT_EXISTS:67000');
  socket.emit('NO-EVENT', { name: 'Test' }, (data) => {
    expect(data).toBe('LITERALLY ANY VALUE');
    throw new Error('JUST GO THROW AN ERROR HERE');
  });
  return socket.disconnect();
});
```

I will make my example soon today.

**Comment by ShGKme** [comment]
@jmcdo29 Check out this repository:  
https://github.com/ShGKme/nestjs-ws-e2e

Or this repl (run it in browser):  
https://repl.it/github/ShGKme/nestjs-ws-e2e
