### ISSUE TITLE
[NEW TEST] Microservices

### ISSUE THREAD

**Issue by jmcdo29** [jmcdo29/testing-nestjs#15]
**Feature Test To Be Requested**

Showing how to test microservice could be useful, especially in an e2e context

**Comment by malcolm-kee** [comment]
@jmcdo29 I'm stuck at this in my project. Do you have any pointer on how to trigger EventPattern handler in controller without manually calling it? (I wish to simulate the scenario that will cause NestJS calling it instead of calling manually the method myself)

Would be happy to contribute the example once I figure that out!

**Comment by jmcdo29** [comment]
@malcolm-kee so, I kinda did something recently with a library I'm working on where I created a super simple client application and ran both the client and the server in the same test context. Then, I would call the client via HTTP and let the client call the microservice, test the functionality, return the value, and finish the request. If everything came through properly, it was a success. 

That's a bit of an oversimplification, due to how I wrote the client (it's dynamic to manage different microservice context), but the idea is there.

**Comment by malcolm-kee** [comment]
Do you mean you can start two nest module in a single test and allows them to interact with each other?

**Comment by jmcdo29** [comment]
That's exactly what I mean. You [can see the test here](https://github.com/jmcdo29/ogma/blob/master/integration/test/rpc.spec.ts), the [client here](https://github.com/jmcdo29/ogma/tree/master/integration/src/rpc/client), and the [server here](https://github.com/jmcdo29/ogma/tree/master/integration/src/rpc/server)

**Comment by malcolm-kee** [comment]
Never thought of that. That's so cool! I'll give it a try!

**Comment by malcolm-kee** [comment]
Able to make it work. Thanks @jmcdo29 . I'll make a PR by this week.
