### ISSUE TITLE
Multiple mocked dependencies with the same content

### ISSUE THREAD

**Issue by RafaelEufrazio** [jmcdo29/testing-nestjs#1617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm trying to manually mock 2 dependencies to unit test a specific service, but while one is correctly mocked, jest seems to be attributing the same content to the other dependency. The beginning of the test code is as follows:

```
jest.mock('../../user/user.service');
jest.mock('../../rent/rent.service');

describe('RatingService', () => {
    let service: RatingService;
    let repository: MockType<Repository<RatingORM>>;

    let userService: UserService;
    let rentService: RentService;

    let user: UserORM;

    beforeEach(async () => {

        user = userStub({ random: true });

        const module = await Test.createTestingModule({
            providers: [
                RatingService,
                UserService,
                RentService,
                { provide: getRepositoryToken(RatingORM), useValue: repositoryMockFactory(ratingStub()) },
            ],
        }).compile();

        service = module.get<RatingService>(RatingService);
        repository = module.get(getRepositoryToken(RatingORM));

        userService = module.get<UserService>(UserService);
        rentService = module.get<RentService>(RentService);

        jest.clearAllMocks();
    });
}
```

I've ommited the tests as the file is too long. 

Down here are the relevant mocks of each service:

```
import { userStub } from "../test/stubs/user.stubs";

export const UserService = jest.fn().mockReturnValue({
    byId: jest.fn().mockResolvedValue(userStub()),
    byEmail: jest.fn().mockResolvedValue({}),
    genericFetch: jest.fn().mockResolvedValue({}),
    create: jest.fn().mockResolvedValue({}),
    save: jest.fn().mockResolvedValue(userStub()),
    resolveUserRating: jest.fn().mockResolvedValue(undefined),
});
```

```
export const RentService = jest.fn().mockReturnValue({
    extract: jest.fn().mockResolvedValue({}),
    create: jest.fn().mockResolvedValue({}),
    approve: jest.fn().mockResolvedValue({}),
    cancel: jest.fn().mockResolvedValue({}),
});
```

When printing the userService and rentService objects after getting them from the testing module, both have all functions from the rent service.

The mock file from userService and rentService are entirely different and reside in completely different locations. I've checked and tested all imports and exports, and all seems correct.

I have no idea what's happening here. Can somebody help me?

### Expected behavior

1 - Mocks to be made correctly
2 - Functions to be called correctly
3 - Tests to be passed

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
I'm not sure what this has to do with this repo (other than it generally being test related) but if you can get me a [minimum reproduction](https://minimum-reproduciton.wtf) I can take a look

**Comment by RafaelEufrazio** [comment]
What would a minimum reproduction be?

I'm sorry, just saw that I posted the right problem on the wrong place, should have been on the jest repo.
Anyways, if you could help me with this I'd appreciate it.

**Comment by jmcdo29** [comment]
Edited the link in my first message. It would explain what a minimum reproduction is

**Comment by RafaelEufrazio** [comment]
Oh I see, I'll try to create a small nestjs project reproducing the problem.

**Comment by RafaelEufrazio** [comment]
I just solved the problem. The issue was that the nestjs dependencies were outdated, I updated the main ones from 7.4.2 to 8.3.1 and the problem went away.

Thanks for your attention anyway. I'm closing this issue.
