### ISSUE TITLE
[NEW TEST] - (Contract Testing) - Incorporate NestJS Consumer Driven Contract testing with nestjs-pact

### ISSUE THREAD

**Issue by YOU54F** [jmcdo29/testing-nestjs#1676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Test To Be Requested

Hey,

Great repo <3

The member of the Pact OSS community recently developed with a NestJS Pact adapter to allow for easy consumer driven contract testing with Pact in a NestJS project.

You can see the repo here https://github.com/omermorad/nestjs-pact

and find our how Pact and Consumer Driven Testing works [here](https://pactflow.io/how-pact-works/?utm_source=ossdocs&utm_campaign=getting_started#slide-1)

I would be happy to work on the examples.

cc: @omermorad

**Comment by jmcdo29** [comment]
I'd love to see an example and PR to the repo for this! I recently started using [`pactum`](https://pactumjs.github.io) instead of supertest for my personal tests and have absolutely loved it. I'd be excited to see what an example for Pact looks like.

**Comment by YOU54F** [comment]
Hey @jmcdo29 

Awesome! Yeah I have seen `pactum`, and love what they are doing, great to see the open Pact specification being used by other parties <3

Couple of links to our nestjs examples from our `pact-js` implementation

- https://github.com/pact-foundation/pact-js/tree/master/examples/nestjs-consumer
- https://github.com/pact-foundation/pact-js/tree/master/examples/nestjs-provider

Will look to get an example in but juggling many things at the moment, so won't be immediate, but I've got this to track.

If anyone wants to help out, the examples above and the readme https://github.com/omermorad/nestjs-pact should possibly provide enough of a cookie trail.

Excited to get involved buddy!

**Comment by jmcdo29** [comment]
> Hi @jmcdo29 @YOU54F,
> 
> Happy to see that! Did you see that I've added nestjs-pact to the list here in the repo?

I'm sorry @omermorad, where do you add it?

**Comment by omermorad** [comment]
@jmcdo29 sorry, I thought we are talking about [awesome-nestjs ](https://github.com/nestjs/awesome-nestjs) repo, and I meant that nestjs-pact is under the list of test utils there

**Comment by YOU54F** [comment]
nice, I hadn't seen that list. Added a badge 😎  https://github.com/nestjs/awesome-nestjs/pull/214
