### ISSUE TITLE
Unable to commit the file in file-up-and-down-sample

### ISSUE THREAD

**Issue by neerajkumar161** [jmcdo29/testing-nestjs#1995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I was doing some type assertion fix in the file, after doing that when I tried to commit the file, ```.eslintrc.json``` file causing the issue and unable to commit the file. You can check the screenshot I have shared. I tried installing the package as well as mentioned in the terminal, but it didn't work. Please let me know if I'm missing anything.

![image](https://github.com/jmcdo29/testing-nestjs/assets/50705472/a24cf4fe-20b4-43f7-bbb7-334022f62a68)

### Expected behavior

File should commit after making changes.

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
Most likely the auto upgrade deps went through fine but there's actual errors with the workout.. nx recently rebranded most of their packages to be `@nx/whatever`.. I'll look into fixing things up tomorrow or Friday
