### ISSUE TITLE
Can't push to sidebranch for PR - getting permission denied

### ISSUE THREAD

**Issue by manzurola** [jmcdo29/testing-nestjs#2004]
`remote: Permission to jmcdo29/testing-nestjs.git denied to manzurola.`

Do I need a token or something?

I have a new mock example app ready and some readme fixes

**Comment by jmcdo29** [comment]
Fork the repo, set a git remote to your fork, make changes locally after climbing either the fork or the main, push changes to the **fork**, and pull request from the fork to the origin
