### ISSUE TITLE
mongodb-transaction-sample/project.json incorrect jest.config reference

### ISSUE THREAD

**Issue by victor-letunovsky** [jmcdo29/testing-nestjs#2010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In `apps/mongodb-transaction-sample/project.json` there is a reference to `apps/mongodb-transaction-sample/jest.config.ts`.
But there is no such config. There is `jest.config.js`, but not `.ts`.

That's why I have `mongodb-transaction-sample` test failing:
```
    ×  nx run mongodb-transaction-sample:test
       >  NX   Can't find a root directory while resolving a config file path.

          Provided path to resolve: D:\Projects\github.com\testing-nestjs\apps\mongodb-transaction-sample\jest.config.ts
          cwd: D:\Projects\github.com\testing-nestjs
          Pass --verbose to see the stacktrace.
```

### Minimum reproduction code and/or steps to reproduce

`pnpm test`

### Expected behavior

`mongodb-transaction-sample` test pass:
```
√  nx run mongodb-transaction-sample:test (27s)
```

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
#2011
