### ISSUE TITLE
[NEW TEST] Automated E2E Testing

### ISSUE THREAD

**Issue by jmcdo29** [jmcdo29/testing-nestjs#354]
Use Dockerfiles and `docker-compose` to allow for E2E tests to be run via GitHub Actions. This will allow for even better tracking of changes to the NestJS Ecosystem and will help others know the E2E tests are working properly

**Comment by malcolm-kee** [comment]
@jmcdo29  Are we looking at including test coverage for the setup, or we're just looking at able to run the e2e test as starter?

**Comment by jmcdo29** [comment]
As a start, just ensuring they run properly. Coverage can be updated later

**Comment by malcolm-kee** [comment]
I'll try to setup for my project and contribute once I figure it out.

**Comment by malcolm-kee** [comment]
Manage to get something working for my project here: https://github.com/malcolm-kee/dine-in/blob/master/.github/workflows/e2e-test.yaml

@jmcdo29 do you have any suggestion for the examples of the container-ized tests? Should we create separate example or we use existing sample by adding more configuration/code?

**Comment by jmcdo29** [comment]
@malcolm-kee I kind of like using the existing samples, but if it is easier to create a separate sample, then let's go with that if it will still be extensible.

**Comment by malcolm-kee** [comment]
Thinking out loud on the E2E Testing example. @jmcdo29  If you have any idea to simplify it, that would be great!

## 2 Apps Will Be Created

- `e2e-example-redis-publisher` have a single REST endpoint, which when called will publish an event to redis
- `e2e-example-redis-subscriber` will listen to the event from redis and save the data in mongoDB. It also expose a single REST endpoint which can be called to retrieve the saved data.

`Dockerfile` on how to build each apps will be available in their respective folder. 

## A `e2e-testing` folder will be added for E2E test scripts

The endpoints of the request will be injected by environment variables.

## A single `docker-compose.yaml` file in the project root

- The apps and the test scripts will be listed here. We'll let Docker Compose to figure out which apps to bring up when we `docker-compose run` in GitHub Actions.
