### ISSUE TITLE
TypeORM and e2e testing

### ISSUE THREAD

**Issue by ShGKme** [jmcdo29/testing-nestjs#380]
I think, full e2e testing with database is an interesting problem. But in TypeORM Sample there is no `cats.e2e-test`.

If we don't mock the DB and make e2e tests mostly near to real environment, there are some interesting things:
- DB creation (sync, migrations, seeds, dumps)
- Running in parallel (databeses must be separated. More intersting if we use not sqlite with in-memory)

It seems to me, that's important part of testing, but may be  a bit of overhead. What do you think?

**Comment by jmcdo29** [comment]
That's actually part of the reason #354 is open, I'm wanting to get all of the e2e tests running through Docker so each environment is separated and they can be run in CI/CD like the unit tests already are. It is a lot of overhead to work with though, and as it is a monorepo, it adds another level of complexity. It's something I've been trying to work on for a while when I have the time. If you have experience, I'm absolutely happy to have some help with parts at a time.

**Comment by jmcdo29** [comment]
Going to close this as #354 is still open and there hasn't been any more conversation here
