### ISSUE TITLE
[FAILING TEST] The try catch tests are passing even with not getting to the evaluation

### ISSUE THREAD

**Issue by BoKKeR** [jmcdo29/testing-nestjs#418]
**Describe the bug**
https://github.com/jmcdo29/testing-nestjs/blob/dfb0c657271b152d27fe4977e946bbaf7527b7d5/apps/complex-sample/src/cat/cat.service.spec.ts#L43-L50
**To Reproduce**
just remove the line in the try block
**Expected behavior**
Without anything in the try block this test should fail because it expects an error to be thrown. But it passes because it never gets to the catch part 
**Desktop (please complete the following information):**
 - OS: [e.g. Windows, MacOS, Linux (which distro)] MacOS
 - Version: [Which version of Nest are you running?] 
```
    "@nestjs/common": "^6.11.11",
    "@nestjs/core": "^6.11.11",
```

Could be fixed by throwing an error inside the try block after the service call. 

`throw new Error('Test was force-failed');`  
or one of many other methods listed here  https://codewithhugo.com/jest-force-explicitly-fail-test/

**Comment by jmcdo29** [comment]
Hmm, I see what you mean by the test will pass even though there are `expect` function in the `catch` block. Maybe some sort of assertion should be made after the service method call, save the result to a value and assert that value? I'm not sure we'd want to throw another error, as that would be caught by the catch block, though that could force the test to fail too. Maybe the test should be changed to use `.rejects.toEqual(new BadRequestException(...))`. That way it follows the idiomatic way of testing according to the link you provided. Would you like to help with a PR for this?

**Comment by jmcdo29** [comment]
#421 will fix this. Thanks for bringing it up!
