### ISSUE TITLE
[NEW TEST]some test cases for axios request?

### ISSUE THREAD

**Issue by jeoy** [jmcdo29/testing-nestjs#423]
**Feature Test To Be Requested**
A clear and concise description of what feature you want to be shown tests for (e.g. Authentication):
Hi Jay,

Could you add some test cases for axios request?

I am not sure if I should use mock axios or real axios request  in this case when test in e2e

Thanks

**Comment by jeoy** [comment]
Or can you give some advice do we need mock axios request for e2e test?

**Comment by jmcdo29** [comment]
By "Axios" are you meaning the npm package, or the built in `HttpService` that is a wrapper around axios?

**Comment by jeoy** [comment]
> By "Axios" are you meaning the npm package, or the built in `HttpService` that is a wrapper around axios?

what's the difference between this two ?
Consider that our service depend on other http service where we use axios (or fetch)  to get data from

**Comment by jmcdo29** [comment]
> What's the difference between these two?
The built in `HttpService` is a wrapper around axios and uses Observables, whereas axios the npm package is a direct http client that uses promises or callbacks, so the testing of the two is different. 

How do your see this test going, are you using a package directly or a service as a wrapper? In my opinion one is easier to work with than the other when it comes to writing tests.

**Comment by jeoy** [comment]
Well, i am using a npm package directly.      
```
import axios  from 'axios';

axios.get(url).then(res => {... })
```

**Comment by jmcdo29** [comment]
If this isn't about mocking a `provider` in Nest, I would say that it falls out of the scope of what this repository is for. There are several tutorials and articles out there showing how you can use `jest.mock()` and `jest.spyOn()` along with other methods to mock npm packages in unit or e2e scopes, as Jest doesn't consider them different at all.

**Comment by jeoy** [comment]
ok cool

**Comment by SSmale** [comment]
sorry to jump on this question but I am having an issue testing a service that uses the `HTTPService` so wondered if there was an example of the spec file?
