### ISSUE TITLE
gitads link doesn't work

### ISSUE THREAD

**Issue by nfedyashev** [jmcdo29/testing-nestjs#979]
I'm new to this repo so I started by reading the README.

Not sure yet what's a proper fix to this by reading this paragraph:

>testing-nestjs is being sponsored by the following tool; please help to support us by taking a look and signing up to a free trial

is a bit confusing because there isn't any clickable links or embedded images being shown. After some investigation I noticed the gitads link:

```
<a href="https://tracking.gitads.io/?repo=testing-nestjs">
 <img src="https://images.gitads.io/testing-nestjs" alt="GitAds"/>
</a>
```
Not sure what was there before but it doesn't seem to work at the moment:

> Not found - Request ID: 89820bc6-de74-4e79-bbb0-ccfeb24a8e25-1826118

**Comment by jmcdo29** [comment]
Ah, yep. Been meaning to remove that. GitAds stopped functioning a little while back. Thanks for reporting this and reminding me :smile:
